export function profileToClient(profile: any) {
  if (!profile) return null
  return {
    id: profile.id,
    first_name: profile.firstName || null,
    last_name: profile.lastName || null,
    passport_photo_url: profile.passportPhotoUrl || null,
    nationality: profile.nationality || null,
    gender: profile.gender || null,
    date_of_birth: profile.dateOfBirth ? new Date(profile.dateOfBirth).toISOString() : null,
    phone_number: profile.phoneNumber || null,
    email: profile.email || null,
    designation: profile.designation || null,
    organization_name: profile.organizationName || null,
    document_type: profile.documentType || null,
    document_number: profile.documentNumber || null,
    signature_data: profile.signatureData || null,
    declaration_accepted: !!profile.declarationAccepted,
    membership_fee_paid: !!profile.membershipFeePaid,
    payment_status: profile.paymentStatus || null,
    payment_reference: profile.paymentReference || null,
    test_completed: !!profile.testCompleted,
    test_score: typeof profile.testScore === 'number' ? profile.testScore : null,
    certificate_issued: !!profile.certificateIssued,
    certificate_url: profile.certificateUrl || null,
    certificate_available_at: profile.certificateAvailableAt ? new Date(profile.certificateAvailableAt).toISOString() : null,
    role_id: profile.roleId || null,
    role: profile.role ? { id: profile.role.id, name: profile.role.name, display_name: profile.role.displayName } : null,
    is_active: !!profile.isActive,
    last_login_at: profile.lastLoginAt ? new Date(profile.lastLoginAt).toISOString() : null,
    login_count: typeof profile.loginCount === 'number' ? profile.loginCount : 0,
    created_at: profile.createdAt ? new Date(profile.createdAt).toISOString() : null,
    updated_at: profile.updatedAt ? new Date(profile.updatedAt).toISOString() : null,
  }
}
